apiVersion: v1
kind: Secret
metadata:
  name: thanos-secret
type: Opaque
stringData:
  objstore.yml: |
    type: s3
    config:
      bucket: "thanos-blocks"
      endpoint: "minio-service:9000"
      region: "us-east-1"      # MinIO doesn't care about region, but S3 requires it
      access_key: "thanos"
      secret_key: "supersecretpassword"
      insecure: true # Use insecure connection for MinIO (HTTP, not HTTPS)