apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-application
  labels:
    app: nodejs-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-application
  template:
    metadata:
      labels:
        app: nodejs-application
    spec:
      containers:
      - name: nodejs-application
        image: nodejs-application:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-application
  labels:
    app: nodejs-application
spec:
  selector:
    app: nodejs-application
  ports:
  - port: 80
    targetPort: 5000
    name: http
  type: ClusterIP