apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-application
  labels:
    app: python-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-application
  template:
    metadata:
      labels:
        app: python-application
    spec:
      containers:
      - name: python-application
        image: python-application:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-application
  labels:
    app: python-application
spec:
  selector:
    app: python-application
  ports:
  - port: 80
    targetPort: 5000
    name: http
  type: ClusterIP