apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: csv-processor
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: csv-processor
          image: csvprocessor:latest
          imagePullPolicy: Never # <--- ADD THIS LINE!
          env:
          - name: REDIS_HOST
            value: redis
          - name: REDIS_LIST
            value: csvs-to-process
          resources:
            limits:
              cpu: "0.2"
              memory: "100Mi"
            requests:
              cpu: "0.2"
              memory: "100Mi"

          volumeMounts:
          - name: data-volume
            mountPath: /app/data
        volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
        restartPolicy: Never
  pollingInterval: 10
  maxReplicaCount: 5

  triggers:
  - type: redis
    metadata:
      address: redis.default:6379
      listName: csvs-to-process
      dataType: list
      name: redis-trigger
      queueName: csvs-to-process
