apiVersion: batch/v1
kind: Job
metadata:
  name: data-generator
spec:
  template:
    spec:

      containers:
      - name: data-generator
        image: datagenerator:latest
        imagePullPolicy: IfNotPresent # <--- ADD THIS LINE
        env:
          - name: REDIS_HOST
            value: redis # <--- CHANGE THIS VALUE
          - name: REDIS_LIST
            value: csvs-to-process


        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      restartPolicy: Never
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
