type: S3
config:
  bucket: "thanos-blocks" # MinIO bucket name
  endpoint: "minio:9000"  # MinIO service name and port in docker-compose
  region: "us-east-1"      # MinIO doesn't care about region, but S3 requires it
  access_key: "thanos"
  secret_key: "supersecretpassword"
  insecure: true # Use insecure connection for MinIO (HTTP, not HTTPS)