apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest  # You can specify a particular version, e.g., nginx:1.23.4
    ports:
    - containerPort: 80 # Nginx typically listens on port 80
    resources:
      limits:
        memory: "128Mi" # Limit memory usage to 128 MiB
        cpu: "500m"     # Limit CPU usage to 0.5 CPU core
      requests:
        memory: "64Mi"  # Request 64 MiB of memory
        cpu: "250m"     # Request 0.25 CPU core
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5 # Wait 5 seconds before first probe
      periodSeconds: 5       # Check every 5 seconds
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5 # Wait 5 seconds before first probe
      periodSeconds: 5       # Check every 5 seconds
    imagePullPolicy: IfNotPresent # <-- CORRECTED: This is now under the container definition
